<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>jp.kwebs</groupId>
	<artifactId>part2</artifactId>
	<name>part1</name>
	<version>0.0.1-SNAPSHOT</version>

	<repositories>
		<repository>
			<id>my-public-repo</id>
			<url>https://k-webs.jp/lecture/m2/repository/</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>jp.kwebs</groupId>
			<artifactId>tools</artifactId>
			<version>1.8.3</version> 
		</dependency>
		<dependency>
			<groupId>jp.kwebs</groupId>
			<artifactId>tkxmail</artifactId>
			<version>3.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>core</artifactId>
			<version>3.5.3</version>
		</dependency>
		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>javase</artifactId>
			<version>3.5.3</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.18.0</version>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<outputDirectory>target/classes</outputDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>25</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>download-sources-javadoc</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>resolve</goal>
						</goals>
						<configuration>
							<downloadSources>true</downloadSources>
							<downloadJavadocs>true</downloadJavadocs>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
